customhost = "employee1.cqiljpncokas.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leejinjian-employee"
customregion = "us-east-1"
